import{a as S,S as q,i}from"./assets/vendor-Db2TdIkw.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const B="49675233-bcad49a609535a7dfe89adf5b",M="https://pixabay.com/api/",R=15;async function m(o,r){const n={key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:R};return(await S.get(M,{params:n})).data}const p=document.querySelector(".gallery"),h=document.querySelector(".load-more"),y=document.querySelector(".loader"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const r=o.map(({webformatURL:n,largeImageURL:a,tags:e,likes:t,views:s,comments:v,downloads:P})=>`
    <div class="gallery-item">
      <a href="${a}">
        <img src="${n}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${t}</p>
        <p><b>Views:</b> ${s}</p>
        <p><b>Comments:</b> ${v}</p>
        <p><b>Downloads:</b> ${P}</p>
      </div>
    </div>
  `).join("");p.insertAdjacentHTML("beforeend",r),$.refresh()}function D(){p.innerHTML=""}function b(){y.classList.remove("hidden")}function L(){y.classList.add("hidden")}function E(){h.classList.remove("hidden")}function l(){h.classList.add("hidden")}const f=document.querySelector(".search-form"),O=document.querySelector(".load-more");let c=1,d="",u=0;const w=15;f.addEventListener("submit",async o=>{o.preventDefault();const n=new FormData(f).get("searchQuery").trim();if(!n){i.warning({message:"Please enter a search query.",position:"topRight"});return}d=n,c=1,D(),l();try{b();const a=await m(d,c);if(u=a.totalHits,a.hits.length===0){i.info({message:"Sorry, no images found. Please try another query.",position:"topRight"});return}g(a.hits),u>w?E():l()}catch{i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}});O.addEventListener("click",async()=>{c+=1;try{b();const o=await m(d,c);g(o.hits);const r=Math.ceil(u/w);c>=r&&(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),A()}catch{i.error({message:"Failed to load more images.",position:"topRight"})}finally{L()}});function A(){const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
